CREATE TABLE
IF NOT EXISTS claire_products
(
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    product_name TEXT NOT NULL,
    max_water_flow TEXT NOT NULL,
    quantity_of_qd TEXT NOT NULL,
    prefiltration TEXT NOT NULL,
    unit_dimensions TEXT NOT NULL,
    expected_life TEXT NOT NULL,
    operating_temperature TEXT NOT Null,
    inlet_outlet TEXT NOT NULL
    
);
