CREATE TABLE
IF NOT EXISTS distributor_list
(
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    region_name TEXT NOT NULL,
    company_name TEXT NOT NULL,
    phone_number TEXT NOT NULL,
    email_address TEXT NOT NULL,
    physical_address TEXT NOT NULL
    
);
