CREATE TABLE IF NOT EXISTS claire_products (
    product_id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    product_name TEXT NOT NULL,
    image TEXT NOT NUll,
    product_descripton TEXT NOT NULL,
    price Text NOT NULL
);
